version: '3.5'
services:


  # Сервер на Django
  nips_django:
    build:
      context: ./server
      dockerfile: DockerFileDjango
      network: host
    container_name: nips_django
    restart: always
    volumes:
      - ./media:/usr/src/app/media
    ports:
      - "9100:8000"
    depends_on:
      - nips_postgres
      - nips_redis
    env_file:
      - ./.env


  # Celery для Django
  nips_celery:
    container_name: nips_celery
    build:
      context: ./server
      dockerfile: DockerFileCelery
      network: host
    depends_on:
      - nips_django
      - nips_redis
      - nips_postgres
    volumes:
      - ./media:/usr/src/app/media
    env_file:
      - ./.env


  # Postgres для Django
  nips_postgres:
    image: postgres
    container_name: nips_postgres
    restart: always
    ports:
      - "9101:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env


  # Redis для Django + Celery
  nips_redis:
    image: redis:alpine


  # Фронт vue.js
  nips_front:
    container_name: nips_front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "9102:8000"