# Generated by Django 3.2.11 on 2022-01-11 10:52

import api_img.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'photo'), ('filter', 'filter'), ('result', 'result')], default='photo', max_length=6, verbose_name='Тип изображения')),
                ('big_image', models.ImageField(blank=True, null=True, upload_to='images/api_img/big/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Файл должен быть одним из: jpg, jpeg'), api_img.models.validate_file_image_max_size], verbose_name='Большое изображение')),
                ('min_image', models.ImageField(blank=True, null=True, upload_to='images/api_img/min/', verbose_name='Маленькое изображение')),
                ('parent_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api_img.imagesmodel', verbose_name='Фильтр родитель')),
                ('parent_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api_img.imagesmodel', verbose_name='Фото родитель')),
            ],
            options={
                'db_table': 'nips_images',
            },
        ),
    ]
